# Generated by Django 4.0 on 2021-12-18 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
