# Generated by Django 4.0 on 2021-12-26 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_chart', '0004_remove_chart_data_chart_remove_chart_data_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testchart_data',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_data', to='tracker_chart.testchart'),
        ),
    ]
